org: redahmeid
app: football-team-management
service: football-team-management
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.create_club
    events:
      - httpApi:
          path: /
          method: post
