org: redahmeid
app: football-team-management
service: football-team-management
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  create_club:
    handler: handler.create_club
    events:
      - httpApi:
          path: /club
          method: post
  retrieve_club:
    handler: handler.create_club
    events:
      - httpApi:
          path: /club
          method: get
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements
