org: redahmeid
app: football-team-management
service: football-team-management
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  environment:
    ENVIRONMENT: ${opt:stage, 'dev'}

functions:
  check_online:
    handler: handler.check_online
    events:
      - http:
          path: /
          method: head
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  create_team_players:
    handler: handler.create_team_players
    events:
      - http:
          path: /teams/{team_id}/players
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  delete_user:
    handler: handler.delete_user
    events:
      - http:
          path: /users
          method: delete
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  contact_us:
    handler: handler.contact_us
    events:
      - http:
          path: /contact_us
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  create_team:
    handler: handler.create_team
    events:
      - http:
          path: /teams
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  create_team_fixtures:
    handler: handler.create_team_fixtures
    events:
      - http:
          path: /teams/{team_id}/matches
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  create_user:
    handler: handler.create_user
    events:
      - http:
          path: /users
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  retrieve_team_squad:
    handler: handler.list_players_by_team
    events:
      - http:
          path: /teams/{team_id}/players
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  retrieve_match_planned_lineups:
    handler: handler.get_match_planned_lineups
    events:
      - http:
          path: /matches/{match_id}/planned_lineups
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  retrieve_match_actual_lineups:
    handler: handler.get_match_actual_lineups
    events:
      - http:
          path: /matches/{match_id}/actual_lineups
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  retrieve_match_current_lineup:
    handler: handler.get_match_current_lineup
    events:
      - http:
          path: /matches/{match_id}/current_lineup
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  user_homepage_bff:
    handler: handler.getUser
    events:
      - http:
          path: /users
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  add_user_to_team:
    handler: handler.add_users_to_team
    events:
      - http:
          path: /teams/{team_id}/users
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  add_guardians_to_player:
    handler: handler.add_guardians_to_player
    events:
      - http:
          path: /teams/{team_id}/players/{player_id}
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  retrieve_matches_by_team:
    handler: handler.list_matches_by_team
    events:
      - http:
          path: /teams/{team_id}/matches
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  retrieve_team_summary:
    handler: handler.retrieve_team_summary
    events:
      - http:
          path: /teams/{team_id}
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  delete_team:
    handler: handler.delete_team
    events:
      - http:
          path: /teams/{team_id}
          method: delete
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  delete_player:
    handler: handler.delete_player
    events:
      - http:
          path: /players/{player_id}
          method: delete
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  retrieve_next_match_by_team:
    handler: handler.retrieve_next_match_by_team
    events:
      - http:
          path: /teams/{team_id}/next_match
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  create_new_team:
    handler: handler.submit_team
    events:
      - http:
          path: /teams
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  
  create_match_day_bff:
    handler: handler.getMatch
    events:
      - http:
          path: /teams/{team_id}/matches/{match_id}
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  
  get_match:
    handler: handler.getMatch
    events:
      - http:
          path: /matches/{match_id}
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
      - http:
          path: /matches/{match_id}/time_played
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  
  submit_lineup:
    handler: handler.submit_lineup
    events:
      - http:
          path: /matches/{match_id}/submit_plan
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  
  set_captain:
    handler: handler.set_captain
    events:
      - http:
          path: /matches/{match_id}/captain
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
      - http:
          path: /matches/{match_id}/potm
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  edit_match:
    handler: handler.edit_match
    events:
      - http:
          path: /matches/{match_id}
          method: patch
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  submit_subs:
    handler: handler.submit_subs
    events:
      - http:
          path: /matches/{match_id}/players/submit_lineup/subs
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  update_match_status:
    handler: handler.update_match_status
    events:
      - http:
          path: /matches/{match_id}/{status}
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  update_matches_from_cache:
    handler: handler.update_matches_from_cache
    events:
      - http:
          path: /matches/from_cache
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  start_match:
    handler: handler.start_match
    events:
      - http:
          path: /matches/{match_id}/start
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
 
  retrieve_score:
    handler: handler.retrieve_score
    events:
      - http:
          path: /matches/{match_id}/score
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  create_jwt:
    handler: handler.set_tokens
    events:
      - http:
          path: /auth/token
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - Etag
            allowCredentials: false
  save_notifications:
    handler: handler.set_device_token
    events:
      - http:
          path: /notifications/token
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  turn_off_notifications:
    handler: handler.turn_off_notifications
    events:
      - http:
          path: /notifications
          method: delete
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  save_notifications_by_match:
    handler: handler.set_device_token_by_match
    events:
      - http:
          path: /notifications/token/{match_id}
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - x-device-id
              - x-api-key
              - authorization
              - ETag
            allowCredentials: false
  subs_due:
    handler: handler.subs_due
  cache_handler:
    handler: handler.cacher
  send_notification:
    handler: handler.sendNotification
 
  

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements
  - serverless-prune-plugin

  # - serverless-domain-manager

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    noDeploy:
     - boto3
     - botocore
  prune:
    automatic: true
    number: 1
  # customDomain:
  #   domainName: sandbox.api.thefootballcoachapp.com  # Replace with your domain name
  #   certificateName: my-certificate  # Replace with your certificate name
  #   stage: devnew  # Optional stage to create the domain name for
  #   createRoute53Record: true 
  # customDomain:
  #   domainName: api.thefootballcoachapp.com  # Replace with your domain name
  #   certificateName: my-certificate  # Replace with your certificate name
  #   stage: prodnew  # Optional stage to create the domain name for
  #   createRoute53Record: true 
    

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
